### ISSUE TITLE
How to use multisig for Bitcoin?

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/satoshi.fund#4]

**Comment by vitalylvov** [comment]
At the moment best solution is to use Copay (it has option to have 6 wallet managers). But there is problem -  there is no way to use advanced send options and change goes to a new address.
This Issue https://github.com/bitpay/copay/issues/981 contains tasks that can solve that problem, but it is on low priority, and doesn't included in any Milestone

Way out:

1. Use Copay "as is" (that means that address book of Fund can be large, but from security side it is right decision)
2. Use Armory (that means that managers have to download BTC Node - not bad, but not usable)
3. Push Copay developers to improve "Advanced Send Options"

We add comments to Copay "Advanced send options"
